// BurgerBuilder actions type
export const NEW_BURGER_IGREDIENT = 'NEW_BURGER_IGREDIENT'
export const REMOVE_BURGER_INGREDIENT = 'REMOVE_BURGER_INGREDIENT'
export const CLEAR_BEFORE_UNMOUNTING = 'CLEAR_BEFORE_UNMOUNTING'