// BurgerBuilder actions type
export const NEW_BURGER_IGREDIENT = 'NEW_BURGER_IGREDIENT'
export const REMOVE_BURGER_INGREDIENT = 'REMOVE_BURGER_INGREDIENT'
export const EMPTY_BURGER = 'EMPTY_BURGER'

export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
export const STOP_PURECHASING = 'STOP_PURECHASING'
export const DEFAULT_PURCHASING_BEFORE_UNMOUNT = 'DEFAULT_PURCHASING_BEFORE_UNMOUNT'

// Checkout 
export const SEND_ALL_USER_DATA = 'SEND_ALL_USER_DATA'

// Orders 
export const RECEIVED_USER_ORDERS = 'RECEIVED_USER_ORDERS'
export const ERROR_RECEIVED_ORDERS = 'ERROR_RECEIVED_ORDERS'
export const CLEAR_ORDERS_BEFORE_UNMOUNT = 'CLEAR_ORDERS_BEFORE_UNMOUNT'

// Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'