// BurgerBuilder actions type
export const NEW_BURGER_IGREDIENT = 'NEW_BURGER_IGREDIENT'
export const REMOVE_BURGER_INGREDIENT = 'REMOVE_BURGER_INGREDIENT'
export const EMPTY_BURGER = 'EMPTY_BURGER'

// Checkout 
export const SEND_ALL_USER_DATA = 'SEND_ALL_USER_DATA'